version: '2'
services:
  config-server:
    build: ./config-server
    restart: always
    ports:
      - '80:80'
  display:
    build: ./display
    restart: always
    ports:
      - '3000:3000'
  browser:
    build: ./browser
    restart: always
    privileged: true
    network_mode: host
  fbcp:
    build: ./fbcp
    restart: on-failure
    privileged: true
  # scheduler:
  #   restart: always
  #   build: ./scheduler
  #   privileged: true
