version: '2'
services:
  config:
    build: ./config
    restart: always
    ports:
      - '80:80'
  display:
    build: ./display
    restart: always
    ports:
      - '82:82'
  api:
    build: ./api
    restart: always
    ports:
      - '84:84'
  browser:
    build: ./browser
    restart: always
    privileged: true
    network_mode: host
  fbcp:
    build: ./fbcp
    restart: on-failure
    privileged: true
  # scheduler:
  #   restart: always
  #   build: ./scheduler
  #   privileged: true
