version: '2'
services:
  backend-server:
    build: ./backend-server
    restart: always
    ports:
      - '80:80'
  sign-server:
    build: ./sign-server
    restart: always
    ports:
      - '82:82'
  browser:
    build: ./browser
    restart: always
    privileged: true
    network_mode: host
  fbcp:
    build: ./fbcp
    restart: on-failure
    privileged: true
  # scheduler:
  #   restart: always
  #   build: ./scheduler
  #   privileged: true
